version: "3"
services:
  arang_bank2:
    build: ./docker/flask/
    container_name: arang_bank2
    volumes:
      - ./app:/app
    stdin_open: true
    environment:
      LC_ALL: C.UTF-8
      FLAG: "flag{hahahahaha}"
    tty: true
    ports:
      - "9002:9002"
    depends_on:
      - db2
      
  db2:
    build: ./docker/mysql
    container_name: mysql-db2
    environment:
      MYSQL_ROOT_PASSWORD: "mysq1_r00t_p4ssw0rd_d0_n0t_cr4ck_th1s!!!@!@!"
    volumes:
      - "./mysql/:/docker-entrypoint-initdb.d/"
    command: mysqld --innodb-buffer-pool-size=16M --character-set-server=utf8 --collation-server=utf8_general_ci 